### ISSUE TITLE
Compile error in linux

### ISSUE THREAD

**Issue by JeroenLeiden** [Bobcatmodder/SAATunes#1]
I get the following errors.

Arduino/libraries/SAATunes/SAATunes.h:21:21: fatal error: arduino.h: No such file or directory
Arduino/libraries/SAATunes/SAATunes.cpp:60:21: fatal error: arduino.h: No such file or directory

The filename should start with a capital A since linux is case sensitive.
When I change it to Arduino.h it does work.

**Comment by Bobcatmodder** [comment]
Thanks for the info! I'll make the change. Have fun with your project!

**Comment by Bobcatmodder** [comment]
Should be fixed now. Let me know if you run into anything else!
