### ISSUE TITLE
Proting for esp8266

### ISSUE THREAD

**Issue by LucaCarrero** [Bobcatmodder/SAATunes#3]
Hi,
i found and made your fantastic project, but i would like use it whit esp8266. Can you help me to do this porting?
Thank you.

**Comment by Bobcatmodder** [comment]
Hi Luca, glad to hear you're enjoying the project! I don't have time to help with an ESP8266 port at the moment. Most of the code should work once a few key pieces are ported. The pieces that would need changing are these:
- The timer interrupts would need to be changed to work with the ESP8266
- The code uses PORTB to write data in parallel to the chip. I don't remember if the ESP8266 has parallel accessible. You could either write some code to emulate a parallel port (takes a byte, writes it to 8 digital output pins) or you could add a serial-to-parallel chip into the mix and send it bytes over Serial. 

Good luck!

**Comment by LucaCarrero** [comment]
I did it. 
I use pcf8575 for data BUS and esp8266 timer library.

https://github.com/LucaCarrero/SAATunes

Happy new year.
